services:
    caddy:
        build:
            context: docker/caddy
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
            - "8888:8888"
        volumes:
            - $PWD/docker/caddy/Caddyfile:/etc/caddy/Caddyfile
            - $PWD:/srv
            - caddy_data:/data
            - caddy_config:/config

    php-fpm:
        build:
            context: docker/php-fpm
        depends_on:
            - database
        volumes:
            - $PWD:/srv
        links:
            - database

    database:
        image: 'mariadb:10'
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD-root}
            MYSQL_DATABASE: ${MYSQL_DATABASE-database}
            MYSQL_USER: ${MYSQL_USER:-iamthebestdev}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-thebestpasswordoftheworld}
        ports:
            - '3306'

    phpmyadmin:
        build:
            context: docker/phpmyadmin
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
            MYSQL_USER: ${MYSQL_USER:-iamthebestdev}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-thebestpasswordoftheworld}
            PMA_HOST: database
            UPLOAD_LIMIT: 50M
        depends_on:
            - database
        links:
            - database

volumes:
    caddy_data:
    caddy_config: