services:
    caddy:
        build:
            context: docker/caddy
        restart: unless-stopped
        ports:
            - "${PORT_SYMFONY:-443}:${PORT_SYMFONY:-443}"
            - "${PORT_PHPMYADMIN:-8888}:${PORT_PHPMYADMIN:-8888}"
        volumes:
            - $PWD/docker/caddy/Caddyfile:/etc/caddy/Caddyfile
            - $PWD:/srv
            - caddy_data:/data
            - caddy_config:/config
        environment:
            PORT_SYMFONY: ${PORT_SYMFONY:-443}
            PORT_PHPMYADMIN: ${PORT_PHPMYADMIN:-8888}
            TZ: ${TIMEZONE:-Europe/Paris}

    php-fpm:
        build:
            context: docker/php-fpm
            args:
                USER_ID: ${USER_ID}
                GROUP_ID: ${GROUP_ID}
                PHP_VERSION: ${PHP_VERSION:-8}
        environment:
            CUSTOM_REPOSITORY: ${CUSTOM_REPOSITORY:-}
            CUSTOM_REPOSITORY_WITH_GIT_DIR: ${CUSTOM_REPOSITORY_WITH_GIT_DIR:-0}
            SSH_KEY_PATH: ${SSH_KEY_PATH:-}
            SYMFONY_VERSION: ${SYMFONY_VERSION:-}
            TZ: ${TIMEZONE:-Europe/Paris}
        depends_on:
            - database
        volumes:
            - $PWD:/srv
            - ${SSH_KEY_PATH:-/dev/null}:/home/www-data/.ssh/id_rsa
        links:
            - database

    database:
        image: "mariadb:${MARIADB_VERSION:-10}"
        restart: always
        ports:
            - '3306'
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-symfony}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-symfony}
            MYSQL_USER: ${MYSQL_USER:-symfony}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-symfony}
            TZ: ${TIMEZONE:-Europe/Paris}

    phpmyadmin:
        build:
            context: docker/phpmyadmin
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
            MYSQL_USER: ${MYSQL_USER:-symfony}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-symfony}
            PMA_HOST: database
            UPLOAD_LIMIT: 50M
            TZ: ${TIMEZONE:-Europe/Paris}
        depends_on:
            - database
        links:
            - database

volumes:
    caddy_data:
    caddy_config:
