services:
    caddy:
        build:
            context: docker/caddy
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
            - "8888:8888"
        volumes:
            - $PWD/docker/caddy/Caddyfile:/etc/caddy/Caddyfile
            - $PWD:/srv
            - caddy_data:/data
            - caddy_config:/config
        env_file:
            - .env

    php-fpm:
        build:
            context: docker/php-fpm
            args:
                USER_ID: ${USER_ID:-0}
                GROUP_ID: ${GROUP_ID:-0}
        depends_on:
            - database
        volumes:
            - $PWD:/srv
        links:
            - database

    database:
        image: 'mariadb:10'
        restart: always
        ports:
            - '3306'
        env_file:
            - .env

    phpmyadmin:
        build:
            context: docker/phpmyadmin
        restart: always
        environment:
            PMA_HOST: database
            UPLOAD_LIMIT: 50M
        depends_on:
            - database
        links:
            - database
        env_file:
            - .env

volumes:
    caddy_data:
    caddy_config:
