name: CI Symfony Website Docker

on:
    push:
    pull_request:

jobs:
    build:
        name: Docker build
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Pull images
                run: docker-compose pull
            -   uses: satackey/action-docker-layer-caching@v0.0.11
                continue-on-error: true
            -   name: Start services
                run: docker-compose up --build -d
            -   name: Check Symfony HTTP reachability
                run: curl http://localhost
            -   name: Check Symfony HTTPS reachability
                run: curl -k https://localhost
            -   name: Check phpMyAdmin reachability
                run: curl -k https://localhost:8888
